### ISSUE TITLE
Detect reload event

### ISSUE THREAD

**Issue by sheerun** [HenrikJoreteg/hjs-webpack#254]
Hey,

I'd like to clear console on each reload. Is there a way to detect reload event on browser side?

**Comment by lukekarrys** [comment]
Webpack does have a way to detect hot module reloading. See [these examples](https://webpack.github.io/docs/hot-module-replacement.html#examples) in the webpack docs.

If you're using full page refreshes and not HMR I know in Chrome you can change a setting so that the console is cleared after the page refreshes. Here's a screenshot of where the option is:

![screen shot 2016-10-20 at 3 00 22 pm](https://cloud.githubusercontent.com/assets/542108/19579554/271be802-96d6-11e6-8908-decbda19027e.png)

Hope this helps!
