### ISSUE TITLE
Add Nib

### ISSUE THREAD

**Issue by Plummat** [HenrikJoreteg/hjs-webpack#26]
Hey! neat Scaffold. I would say people use nib a lot more than yeticss, so why not throw it in? Just need to add it as a peerdep and require it in the base-config.js file

**Comment by HenrikJoreteg** [comment]
Indeed. Good point.

**Comment by HenrikJoreteg** [comment]
wanna send me a PR? rather busy at the moment.

**Comment by klaemo** [comment]
imho stuff like that should be optional, not hard-required. what do you think? I use neither nib nor yeticss, but gotta have the latter installed atm.

**Comment by chcokr** [comment]
I agree with @klaemo . Having stuff like `yeticss` belong in `peerDependencies` when you don't use `yetis` adds to the time it takes to `npm install` and makes a `package.json` harder to understand.

@lukekarrys

**Comment by lukekarrys** [comment]
I think it's a fine line. For example, right now most people using `hjs-webpack` are probably using `babel` so it makes sense to include that loader by default as a peer dependency I think. I think that CSS preprocessing has more options (stylus, less, sass, etc) and that's not even including plugins like yeticss and nib.

My vote would be to remove `stylus-loader` and `yeticss` from peer dependencies and remove `yeticss` from being preconfigured as a stylus plugin. This way `hjs-webpack` is treating all css preprocessors equally since it will still allow stylus to be used in the same way as less/sass are currently where it detects if you have the loader installed via npm and then adds the loader configuration.

**Comment by klaemo** [comment]
I agree with this solution. `hjs-webpack` should simplify webpack configuration, not prescribe usage of certain tools. Preconfigure the most popular loaders (the ones you mentioned) so they are only an `npm install` away.

**Comment by lukekarrys** [comment]
Curious if @HenrikJoreteg has any thoughts on this? It's a pretty easy change, but I think it should wait until I try to work on #65 which will also be a breaking change.

**Comment by HenrikJoreteg** [comment]
I have thoughts, just been traveling (got hole from Sweden last night). But
yeah, hang tight, I wanna take a peek when I've got a minute.

**Comment by HenrikJoreteg** [comment]
sorry for the delay, my thoughts were basically this: I don't mind if this is made to be a bit more generic, but I think it'd be cool to still have it Just Work™ if you install the dependency. So maybe just using the same if installed check?

**Comment by klaemo** [comment]
I'd be cool with that

**Comment by lukekarrys** [comment]
Closed by #80
