### ISSUE TITLE
html function does not return full context object as stated in documentation

### ISSUE THREAD

**Issue by jeffboyus** [HenrikJoreteg/hjs-webpack#37]
In the html function of the config file, the context argument does not return the CSS filename as stated.  There is no mention in the [documentation](https://github.com/HenrikJoreteg/hjs-webpack#html-optional-can-be-boolean-or-function) of any trigger/option that would make this attribute show up or not.

```javascript
var getConfig = require('hjs-webpack')
var isDev = process.env.NODE_ENV !== 'production'

module.exports = getConfig({
  in: 'src/app.js',
  out: 'build',
  clearBeforeBuild: true,
  isDev: isDev,
  html: function (context) {
    console.log(context); // <-------- no context.css attribute is generated
    return {
      'index.html': '<!DOCTYPE><body><h1>Hello World</h1></body>'
    }
  }
})
```

> Using the LESS styles option. Imported the correct LESS loader.  Works when running in dev and the LESS file is required on a view.  But will not work when running build command (undefined context.css attribute).

**Comment by lukekarrys** [comment]
Hey @jeffboyus, in one of the minor releases lately you no longer have to explicitly set `isDev` (unless you want to according to some other flag) since it will detect if you are using `webpack-dev-server` and will default to `true` only in that case.

So what I think might be happening is that unless you are running `NODE_ENV=production npm run build`, it is setting `isDev` back to `true` which would remove the `context.css` attribute. We don't call that out in the docs, but we probably should.

I setup [a gist here](https://gist.github.com/lukekarrys/f9a62597ebcaaaa85f31) and was able to get `context.css` to show up with the only major change being removing `isDev` from the `webpack.config.js`.

If that doesn't work for you, can you post your `src/app.js` file and the `scripts` section from your `package.json`?

**Comment by jeffboyus** [comment]
Nope, that was it.  Did not see that little piece of info.  Moral of the story: Always check the commit history

**Comment by lukekarrys** [comment]
I just updated the docs with the info about `context.css` missing in production mode so hopefully that will be a bit clearer in the future too.
