### ISSUE TITLE
Changing Babel configuration

### ISSUE THREAD

**Issue by unbracketed** [HenrikJoreteg/hjs-webpack#38]
Leaving this here in case it helps others. Maybe this can fit in the README somewhere?

Here's an example `webpack.config.js` enabling "stage 0" feature support:

```
var getConfig = require('hjs-webpack')

var config = getConfig({
  in: 'src/app.js',
  out: 'public',
  clearBeforeBuild: true
})

config.module.loaders[0].loaders[1] = 'babel-loader?stage=0'
module.exports = config
```

You might notice a hard assumption about where the babel-loader is defined within the module loaders list. If you prefer you can replace 

    config.module.loaders[0].loaders[1] = 'babel-loader?stage=0'

with something like this to be a little more future-proof:

```
config.module.loaders.forEach(function (filter) {
  if (filter.loaders) {
    filter.loaders.forEach(function(loader, idx, arr) {
      if (loader === 'babel-loader') {
        arr[idx] = 'babel-loader?stage=0'
      }
    })
  }
})
```

**Comment by lukekarrys** [comment]
Thanks @unbracketed, I'm actually doing the same thing in a project of mine that uses `hjs-webpack`

 I think it'd be a good idea to have a section in the docs about this, explaining that the output is a JS object so it can be manipulated as such, and show an example. If you're up for a PR for this, it would be greatly appreciated.

I've also tried to think of more elegant solutions to this like providing a `loaders` input option but any intelligent merging of the input and the default loaders would probably be too difficult. (In my project I'm using the `blacklist` query param for `babel` and using `include` instead of `exclude`, etc :smile:).

I'm also curious what would happen if you specified a second `babel-loader` (either at the beginning or end of the loaders array, not sure if it would make a difference) and if that would take precedence over the default? That way `webpack` takes over the difficult part (determining which loader to use) and the user can specify all the options they want without much duplication over what is in the default.

**Comment by unbracketed** [comment]
Thank you for the feedback. I'll put together a PR with some docs suggestions. 

I'll think/poke at whether the loaders can be more declarative and report back if I come up with any interesting strawmen.

**Comment by unbracketed** [comment]
I didn't forget about this :) Wanted to update with a note that you can also use a [`.babelrc`](https://babeljs.io/docs/usage/babelrc/) file for this purpose. Example contents:

```
{
  "stage": 0,
 "optional": "runtime"
}
```
would enable Stage 0 and `babel-runtime` support for generator polyfills.

**Comment by HenrikJoreteg** [comment]
Thanks!

I added a note to the readme explaining that you can use a `.babelrc` file i think that will suffice for this. Re-open if you disagree :)
