### ISSUE TITLE
hostname not working

### ISSUE THREAD

**Issue by yougotashovel** [HenrikJoreteg/hjs-webpack#71]
I'm getting this error *only* when trying to use a hostname in webpack.config.js. I think it's possibly to do with the path to the hostname not being defined. Does anybody have an idea of what's going wrong?

Here's the config:
```
var getConfig = require('hjs-webpack');

module.exports = getConfig({
	in: 'src/app.js',
	out: 'public',
	isDev: process.env.NODE_ENV !== 'production',
	hostname: 'testhost.local'  // if i remove this line, everything works
});
```

Here is the error that terminal is showing.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

Thanks

**Comment by lukekarrys** [comment]
It looks like `testhost.local` doesn't exist so the `webpack-dev-server` can't bind to that address. On my machine I have it set to my computers local host name and it is working, but if I change it to anything else I get the same error.

On my mac running `10.10.5` I'm able to get my local host name by running the following command (and then adding `.local` to the end).

```sh
> scutil --get LocalHostName
lukekarrys
```

**Comment by yougotashovel** [comment]
Works great! Thanks

So just for clarification, the hostname must be the computer hostname, can't be a new name created just for a project.  I'm coming from MAMP where i can set individual app hostnames, that's where my confusion was.

**Comment by lukekarrys** [comment]
I'm not an expert on this, but I'm guessing that MAMP is doing more stuff behind the scenes and creating a custom port for each project and then binding a new hostname to it.

With `hjs-webpack` we allow setting the `hostname` mainly so that you can use other devices (phone, tablet, etc) on your local network to test your project, but it has to exist already.

A quick Google search turned up [`katon`](https://github.com/typicode/katon) as a solution for using custom dev domains for projects. Looks like it would work with `hjs-webpack` but I don't have any experience with it.
