### ISSUE TITLE
Uglify with mangle

### ISSUE THREAD

**Issue by jlc467** [HenrikJoreteg/hjs-webpack#81]
Noticed by default npm run build will concat+minify but not mangle. Is mangle not a best practice? .. wondering if we should have that as an option? With source maps of course.

**Comment by lukekarrys** [comment]
I *think* mangle might not be a good default, since it can break stuff (not 100% sure on that though).

I'd be open to a PR allowing options to be passed directly to [`webpack.optimize.UglifyJsPlugin`](https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin).

**Comment by HenrikJoreteg** [comment]
I'm not quite sure on this either. Need more info.

**Comment by chrisvfritz** [comment]
UglyfiyJS won't mangle top-level names by default, which is what can break things, so there shouldn't be a problem as long as you don't specify `--mangle-toplevel`. 

What I'd recommend though is using [Webpack's built-in optimization parameters](https://github.com/webpack/docs/wiki/optimization). They still use UglifyJS, but will configure it for you (since Webpack knows what it can get away with). The parameter I use on every project, which includes mangling, is `--optimize-minimize` (or `-p`). Nothing's ever broken so far. By including a link to the other parameters in the documentation, folks can also easily configure their build just by updating the parameters in that task - leaving hjs-webpack completely out of it.

**Comment by HenrikJoreteg** [comment]
Thanks, @chrisvfritz I'm good with webpack's defaults if someone wants to tackle this.
