### ISSUE TITLE
Update examples to babel 6

### ISSUE THREAD

**Issue by barbalex** [HenrikJoreteg/hjs-webpack#93]
Warning: Noob question here!

I'm not sure if this is correct but probably I should wait until hjs-webpack is configured for babel 6.

Is this true?

(sorry for spamming your issues)

**Comment by lukekarrys** [comment]
I haven't tried babel 6 yet, but from a quick glance at the docs for babel-loader it doesnt look like the configuration has changed.

Since your babel options will be located in your `.babelrc`, you should be able to following the installation instructions for the latest [`babel-loader`](https://github.com/babel/babel-loader#installation) or check out this [quick upgrade guide](https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53#.yqxukuzdk) to see the easiest way to make the necessary changes in your `.babelrc` and dependencies.

**Comment by lukekarrys** [comment]
I'm going to keep this open too, as a reminder to go through our `examples/` directory and update them to babel 6.

**Comment by barbalex** [comment]
This is a little difficult for me because I never had to choose any babel options before as hjs-webpack did that. So I have no idea, what would be the "necessary" changes.

I tried setting presets 'es2015' and 'react'. But ran into a series of weird errors. So I will forget updating for a while.

**Comment by barbalex** [comment]
I had more luck with a younger project with less dependencies. This works after adding presets 'es2015', 'react' and 'stage-0'

**Comment by lukekarrys** [comment]
> This is a little difficult for me because I never had to choose any babel options before as hjs-webpack did that. So I have no idea, what would be the "necessary" changes.

Hmmm, that's a good point. `hjs-webpack` wasn't setting anything up, but `babel@5` was setup by default to do `react` and `es2015` transforms. Maybe we should consider adding those as default presets when configuring `babel-loader` from now on.

**Comment by barbalex** [comment]
Well, thanks for this great tool. I even got my first project to work now after updating babel. Not closing because you want to keep this open.

**Comment by barbalex** [comment]
and by the way: thanks for stellar help. Your links saved my day

**Comment by lukekarrys** [comment]
:smile: Glad I could help!

**Comment by lukekarrys** [comment]
Closed by #110
